# This file defines the build script for all supported aspnetcore images.
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'generator', './dockerfile_generator' ]
  id: 'generator-build'
  waitFor: ['-']

# Build and test the images.

# .NET Core 1.0.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.0.9-${_TAG}',
          '--no-cache', '--pull', './aspnetcore-1.0/image' ]
  id: 'aspnetcore-1-0-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.0.9-${_TAG}',
         '--config', '/workspace/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-1-0-test'
  waitFor: [ 'aspnetcore-1-0-build' ]

# .NET Core 1.1.x

# .NET Core 2.0.x

# Functional tests.

# .NET Core 1.0.x
- name: generator
  args: [ './functional_tests/published/test-1.0.9', '${_DOCKER_NAMESPACE}/aspnetcore:1.0.9-${_TAG}' ]
  id: 'generator-run-1-0'
  waitFor: [ 'generator-build', 'aspnetcore-1-0-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-1-0', './functional_tests/published' ]
  id: 'test-app-build-1-0'
  waitFor: [ 'generator-run-1-0' ]
- name: test-app-1-0
  id: 'test-app-run-1-0'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 1.0!" ]]' ]
  waitFor: [ 'test-app-build-1-0' ]

# Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.0.9-${_TAG}'
