# This file defines the build script for all supported aspnetcore images.
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'generator', './dockerfile_generator' ]
  id: 'generator-build'
  waitFor: ['-']

# .NET Core 1.0.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.0-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-1.0/image' ]
  id: 'aspnetcore-1-0-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.0-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-1.0/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-1-0-test'
  waitFor: [ 'aspnetcore-1-0-build' ]
- name: generator
  args: [ './versions/aspnetcore-1.0/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:1.0-${_TAG}' ]
  id: 'generator-run-1-0'
  waitFor: [ 'generator-build', 'aspnetcore-1-0-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-1-0', './versions/aspnetcore-1.0/functional_tests/published' ]
  id: 'test-app-build-1-0'
  waitFor: [ 'generator-run-1-0' ]
- name: test-app-1-0
  id: 'test-app-run-1-0'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 1.0!" ]]' ]
  waitFor: [ 'test-app-build-1-0' ]

# .NET Core 1.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.1-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-1.1/image' ]
  id: 'aspnetcore-1-1-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.1-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-1.1/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-1-1-test'
  waitFor: [ 'aspnetcore-1-1-build' ]
- name: generator
  args: [ './versions/aspnetcore-1.1/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:1.1-${_TAG}' ]
  id: 'generator-run-1-1'
  waitFor: [ 'generator-build', 'aspnetcore-1-1-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-1-1', './versions/aspnetcore-1.1/functional_tests/published' ]
  id: 'test-app-build-1-1'
  waitFor: [ 'generator-run-1-1' ]
- name: test-app-1-1
  id: 'test-app-run-1-1'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 1.1!" ]]' ]
  waitFor: [ 'test-app-build-1-1' ]

# .NET Core 2.0.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:2.0-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-2.0/image' ]
  id: 'aspnetcore-2-0-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:2.0-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-2.0/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-2-0-test'
  waitFor: [ 'aspnetcore-2-0-build' ]
- name: generator
  args: [ './versions/aspnetcore-2.0/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:2.0-${_TAG}' ]
  id: 'generator-run-2-0'
  waitFor: [ 'generator-build', 'aspnetcore-2-0-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-2-0', './versions/aspnetcore-2.0/functional_tests/published' ]
  id: 'test-app-build-2-0'
  waitFor: [ 'generator-run-2-0' ]
- name: test-app-2-0
  id: 'test-app-run-2-0'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 2.0!" ]]' ]
  waitFor: [ 'test-app-build-2-0' ]

  # .NET Core 2.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:2.1-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-2.1/image' ]
  id: 'aspnetcore-2-1-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:2.1-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-2.1/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-2-1-test'
  waitFor: [ 'aspnetcore-2-1-build' ]
- name: generator
  args: [ './versions/aspnetcore-2.1/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:2.1-${_TAG}' ]
  id: 'generator-run-2-1'
  waitFor: [ 'generator-build', 'aspnetcore-2-1-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-2-1', './versions/aspnetcore-2.1/functional_tests/published' ]
  id: 'test-app-build-2-1'
  waitFor: [ 'generator-run-2-1' ]
- name: test-app-2-1
  id: 'test-app-run-2-1'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 2.1!" ]]' ]
  waitFor: [ 'test-app-build-2-1' ]

  # .NET Core 2.2.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:2.2-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-2.2/image' ]
  id: 'aspnetcore-2-2-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:2.2-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-2.2/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-2-2-test'
  waitFor: [ 'aspnetcore-2-2-build' ]
- name: generator
  args: [ './versions/aspnetcore-2.2/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:2.2-${_TAG}' ]
  id: 'generator-run-2-2'
  waitFor: [ 'generator-build', 'aspnetcore-2-2-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-2-2', './versions/aspnetcore-2.2/functional_tests/published' ]
  id: 'test-app-build-2-2'
  waitFor: [ 'generator-run-2-2' ]
- name: test-app-2-2
  id: 'test-app-run-2-2'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 2.2!" ]]' ]
  waitFor: [ 'test-app-build-2-2' ]

  # .NET Core 3.0.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:3.0-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-3.0/image' ]
  id: 'aspnetcore-3-0-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:3.0-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-3.0/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-3-0-test'
  waitFor: [ 'aspnetcore-3-0-build' ]
- name: generator
  args: [ './versions/aspnetcore-3.0/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:3.0-${_TAG}' ]
  id: 'generator-run-3-0'
  waitFor: [ 'generator-build', 'aspnetcore-3-0-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-3-0', './versions/aspnetcore-3.0/functional_tests/published' ]
  id: 'test-app-build-3-0'
  waitFor: [ 'generator-run-3-0' ]
- name: test-app-3-0
  id: 'test-app-run-3-0'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 3.0!" ]]' ]
  waitFor: [ 'test-app-build-3-0' ]

  # .NET Core 3.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}',
          '--no-cache', '--pull', './versions/aspnetcore-3.1/image' ]
  id: 'aspnetcore-3-1-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}',
         '--config', '/workspace/versions/aspnetcore-3.1/structural_tests/aspnet.yaml', '-v']
  id: 'aspnetcore-3-1-test'
  waitFor: [ 'aspnetcore-3-1-build' ]
- name: generator
  args: [ './versions/aspnetcore-3.1/functional_tests/published', '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}' ]
  id: 'generator-run-3-1'
  waitFor: [ 'generator-build', 'aspnetcore-3-1-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-3-1', './versions/aspnetcore-3.1/functional_tests/published' ]
  id: 'test-app-build-3-1'
  waitFor: [ 'generator-run-3-1' ]
- name: test-app-3-1
  id: 'test-app-run-3-1'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/app.dll)" == "Hello World 3.1!" ]]' ]
  waitFor: [ 'test-app-build-3-1' ]

  # Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.0-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.1-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:2.0-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:2.1-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:3.0-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:3.1-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:2.2-${_TAG}'
