#! /usr/bin/env bash
# This script builds and pushes the container for the given .Net runtime with
# the right tag.

# Exit on error
set -o errexit

# Load the common settings
workspace="$(dirname $0)"
source "${workspace}/common.sh"

build_docker_image "${workspace}"

push_docker_image

echo Done.
