#! /usr/bin/env bash
# This script builds and pushes the container for the given .Net runtime with
# the right tag.
#   $1: The name of the runtime to build.

# Exit on error
set -o errexit

# Load the common settings
workspace="$(dirname $0)"
source "${workspace}/common.sh"

runtime_name="${1:-mono}"

build_docker_image "${workspace}" "${runtime_name}"

push_docker_image "${runtime_name}"

echo Done.
