#! /usr/bin/env bash
# This script will run the ocntainer for the given .NET runtime.
#   $1: The name of the runtime to build.

# Exit on error
set -o errexit

# Load the common settings
workspace="$(dirname $0)"
source "${workspace}/common.sh"

run_docker_image
