# This file defines how the ASP.NET Core 2.0 images are to be built and
# published. The file expects the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the runtime images in parallel.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:2.0.0-${_TAG}', './versions/2.0.0' ]
  id: 'aspnetcore-2-0-0-build'

# Test the images structure.
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:2.0.0-${_TAG}',
         '--config', '/workspace/structural_tests/2.0.0/aspnet.yaml', '-v']
  id: 'aspnetcore-2-0-0-test'

# Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcore:2.0.0-${_TAG}'
