# This file defines how the builder image is built. The file expects
# the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the test validator image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-validator', '--no-cache', '--pull', './functional_tests_validator' ]
  id: 'test-validator-build'
  waitFor: ['-']

# Builds the Dockerfile validator.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'dockerfile-validator', './dockerfile_validator' ]
  id: 'dockerfile-validator-build'
  waitFor: ['-']

# Build the builder image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}',
          '--no-cache', '--pull', './src' ]
  id: 'builder-build'
  waitFor: ['-']

# Test the images structure.
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}',
         '--config', '/workspace/structural_tests/aspnet.yaml', '-v']
  id: 'builder-structural-test'
  waitFor: [ 'builder-build' ]

# Test builder functionality with pre-published apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-1.0'
  id: 'builder-functional-test-1-0'
  waitFor: [ 'builder-build' ]
- name: 'test-validator'
  args:
    - 'functional_tests/clean-1.0'
    - 'aspnetcore:1.0'
    - 'clean-1.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-1-0' ]
  id: 'test-validator-clean-1-0'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleanjs-1.0'
  id: 'builder-functional-test-js-1-0'
  waitFor: [ 'builder-build' ]
- name: 'test-validator'
  args:
    - 'functional_tests/cleanjs-1.0'
    - 'aspnetcore:1.0'
    - 'cleanjs-1.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-js-1-0' ]
  id: 'test-validator-cleanjs-1-0'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-1.1'
  id: 'builder-functional-test-1-1'
  waitFor: [ 'builder-build' ]
- name: 'test-validator'
  args:
    - 'functional_tests/clean-1.1'
    - 'aspnetcore:1.1'
    - 'clean-1.1'
  waitFor: [ 'test-validator-build', 'builder-functional-test-1-1' ]
  id: 'test-validator-clean-1-1'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-2.0'
  id: 'builder-functional-test-2-0'
  waitFor: [ 'builder-build' ]
- name: 'test-validator'
  args:
    - 'functional_tests/clean-2.0'
    - 'aspnetcore:2.0'
    - 'clean-2.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-2-0' ]
  id: 'test-validator-clean-2-0'

# Test the functionality for single project apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansource-1.0'
  id: 'builder-functional-cleansource-1-0'
  waitFor: [ 'builder-build' ]
- name: 'dockerfile-validator'
  args: 'functional_tests/cleansource-1.0'
  id: 'dockerfile-validator-cleansource-1-0'
  waitFor: [ 'dockerfile-validator-build', 'builder-functional-cleansource-1-0' ]

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansource-1.1'
  id: 'builder-functional-cleansource-1-1'
  waitFor: [ 'builder-build' ]
- name: 'dockerfile-validator'
  args: 'functional_tests/cleansource-1.1'
  id: 'dockerfile-validator-cleansource-1-1'
  waitFor: [ 'dockerfile-validator-build', 'builder-functional-cleansource-1-1' ]

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansource-2.0'
  id: 'builder-functional-cleansource-2-0'
  waitFor: [ 'builder-build' ]
- name: 'dockerfile-validator'
  args: 'functional_tests/cleansource-2.0'
  id: 'dockerfile-validator-cleansource-2-0'
  waitFor: [ 'dockerfile-validator-build', 'builder-functional-cleansource-2-0' ]

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/fsharp-2.0'
  id: 'builder-functional-fsharp-2-0'
  waitFor: [ 'builder-build' ]
- name: 'dockerfile-validator'
  args: 'functional_tests/fsharp-2.0'
  id: 'dockerfile-validator-fsharp-2-0'
  waitFor: [ 'dockerfile-validator-build', 'builder-functional-fsharp-2-0' ]

# Test the functionality for solution based apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '-m'
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansolution-2.0'
  id: 'builder-functional-cleansolution-2-0'
  waitFor: [ 'builder-build' ]
- name: 'dockerfile-validator'
  args: 'functional_tests/cleansolution-2.0'
  id: 'dockerfile-validator-cleansolution-2-0'
  waitFor: [ 'dockerfile-validator-build', 'builder-functional-cleansolution-2-0' ]

# Publish the image.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
