# This file defines how the builder image is built. The file expects
# the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the test validator image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-validator', '--no-cache', '--pull', './functional_tests_validator' ]
  id: 'test-validator-build'
  waitFor: ['-']

# Build the builder image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}',
          '--no-cache', '--pull', './src' ]
  id: 'builder-build'
  waitFor: ['-']

# Test the images structure.
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}',
         '--config', '/workspace/structural_tests/aspnet.yaml', '-v']
  id: 'builder-structural-test'
  waitFor: [ 'builder-build' ]

# Test builder functionality with pre-published apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-1.0'
  id: 'builder-functional-test-1-0'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-clean-1-0'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:1.0'
    - 'clean-1.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-1-0' ]
  id: 'test-validator-clean-1-0'
  volumes:
  - name: 'published-clean-1-0'
    path: '/published'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleanjs-1.0'
  id: 'builder-functional-test-js-1-0'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-cleanjs-1-0'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:1.0'
    - 'cleanjs-1.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-js-1-0' ]
  id: 'test-validator-cleanjs-1-0'
  volumes:
  - name: 'published-cleanjs-1-0'
    path: '/published'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-1.1'
  id: 'builder-functional-test-1-1'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-clean-1-1'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:1.1'
    - 'clean-1.1'
  waitFor: [ 'test-validator-build', 'builder-functional-test-1-1' ]
  id: 'test-validator-clean-1-1'
  volumes:
  - name: 'published-clean-1-1'
    path: '/published'

- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/clean-2.0'
  id: 'builder-functional-test-2-0'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-clean-2-0'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:2.0'
    - 'clean-2.0'
  waitFor: [ 'test-validator-build', 'builder-functional-test-2-0' ]
  id: 'test-validator-clean-2-0'
  volumes:
  - name: 'published-clean-2-0'
    path: '/published'

# Test builder functionality with project apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansource-1.0'
  id: 'builder-functional-cleansource-1-0'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-cleansource-1-0'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:1.0'
    - 'cleansource-1.0'
  waitFor: [ 'test-validator-build', 'builder-functional-cleansource-1-0' ]
  id: 'test-validator-cleansource-1-0'
  volumes:
  - name: 'published-cleansource-1-0'
    path: '/published'

# Test builder functionality with solution apps.
- name: '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
  args:
    - '1.1.2=aspnetcore:1.1'
    - '1.0.5=aspnetcore:1.0'
    - '2.0.0=aspnetcore:2.0'
  dir: 'functional_tests/cleansolution-2.0'
  id: 'builder-functional-cleansolution-2-0'
  waitFor: [ 'builder-build' ]
  volumes:
  - name: 'published-cleansolution-2-0'
    path: '/published'
- name: 'test-validator'
  args:
    - '/published'
    - 'aspnetcore:2.0'
    - 'MainProject'
  waitFor: [ 'test-validator-build', 'builder-functional-cleansolution-2-0' ]
  id: 'test-validator-cleansolution-2-0'
  volumes:
  - name: 'published-cleansolution-2-0'
    path: '/published'

# Publish the image.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcorebuildexp:${_TAG}'
