# This file defines how the ASP.NET Core 1.1 images are to be built and
# published. The file expects the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the runtime images in parallel.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.1-${_TAG}',
          '--no-cache', '--pull', './versions/1.1.1' ]
  id: 'aspnetcore-1-1-1-build'
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.2-${_TAG}',
          '--no-cache', '--pull', './versions/1.1.2' ]
  id: 'aspnetcore-1-1-2-build'
  waitFor: ['-']

# Test the images structure.
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.1-${_TAG}',
         '--config', '/workspace/structural_tests/1.1.1/aspnet.yaml', '-v']
  id: 'aspnetcore-1-1-1-test'
  waitFor: [ 'aspnetcore-1-1-1-build' ]
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.2-${_TAG}',
         '--config', '/workspace/structural_tests/1.1.2/aspnet.yaml', '-v']
  id: 'aspnetcore-1-1-2-test'
  waitFor: [ 'aspnetcore-1-1-2-build' ]

# Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.1.1-${_TAG}'
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.1.2-${_TAG}'
