#! /usr/bin/env bash
# This script builds the image with the right tag.

# Exit on error
set -eu

# Load the common settings
readonly tools="$(dirname $0)"
readonly repo="${tools}/.."
source "${tools}/common.sh"

build_docker_image "${repo}/dotnet_runtime"

echo Done.
