#! /usr/bin/env bash
# This script builds the container for the given .NET runtime with the right tag

# Exit on error
set -eu

# Load the common settings
readonly tools="$(dirname $0)"
readonly repo="${tools}/.."
source "${tools}/common.sh"

build_docker_image "${repo}/dotnet_runtime"

echo Done.
