#! /usr/bin/env bash
# This script builds the container for the .NET runtime with the right tag.

# Exit on error
set -o errexit

# Load the common settings
readonly workspace="$(dirname $0)/.."
source "${workspace}/tools/common.sh"

build_docker_image "${workspace}/aspnet_runtime"

echo Done.
