#! /usr/bin/env bash
# This script builds and pushes the image runtime with the right tag.

# Exit on error
set -eu

# Load the common settings
readonly tools="$(dirname $0)"
readonly repo="${tools}/.."
source "${tools}/common.sh"

build_docker_image "${repo}/dotnet_runtime"

push_docker_image

echo Done.
