#! /usr/bin/env bash
# This script builds and pushes the image for the .Net runtime with the right
# tag.

# Exit on error
set -o errexit

# Load the common settings
readonly workspace="$(dirname $0)/.."
source "${workspace}/tools/common.sh"

build_docker_image "${workspace}/aspnet_runtime"

push_docker_image

echo Done.
