#! /usr/bin/env bash
# This script will run the image.

# Exit on error
set -eu

# Load the common settings
readonly tools="$(dirname $0)"
readonly repo="${tools}/.."
source "${tools}/common.sh"

run_docker_image
