#! /usr/bin/env bash
# This script will run the ocntainer for the given .NET runtime.

# Exit on error
set -eu

# Load the common settings
workspace="$(dirname $0)"
source "${workspace}/common.sh"

run_docker_image
