#! /usr/bin/env bash

# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# This script will build the specified build.
#   $1, the path to the cloudbuild.yaml to run.
#   $2, repository for the resulting image.

# Exit on error or undefined variable
set -eu

if [ -z "${1:-}" ]; then
    echo "Must specify the cloudbuild.yaml to run."
    exit 1
fi

readonly workspace=$(dirname $0)/..
source ${workspace}/tools/common.inc

readonly repo=$(get_docker_namespace "${2:-}")

# The TAG environment variable can be used to override the time based TAG
# generated by this script. If the TAG variable is used then it will become the
# unique tag for the image.
if [ -z "${TAG:-}" ]; then
  readonly TAG=$(date +"%Y-%m-%d_%H_%M")
fi

# Start the build.
readonly build_dir=$(dirname $1) 
gcloud container builds submit "${build_dir}" \
    --config="$1" \
    --substitutions _DOCKER_NAMESPACE=${repo},_TAG=${TAG}
