# This file defines how the ASP.NET Core 1.1 images are to be built and
# published. The file expects the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'generator', './functional_tests/dockerfile_generator' ]
  id: 'generator-build'
  waitFor: ['-']

# Build and test the image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.6-${_TAG}',
          '--no-cache', '--pull', './versions/1.1.6' ]
  id: 'aspnetcore-1-1-6-build'
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.6-${_TAG}',
         '--config', '/workspace/structural_tests/1.1.6/aspnet.yaml', '-v']
  id: 'aspnetcore-1-1-6-test'
  waitFor: [ 'aspnetcore-1-1-6-build' ]

# Functional tests.
- name: generator
  args: [ './functional_tests/published/test-1.1.6', '${_DOCKER_NAMESPACE}/aspnetcore:1.1.6-${_TAG}' ]
  id: 'generator-run-1-1-6'
  waitFor: [ 'generator-build', 'aspnetcore-1-1-6-build' ]
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'test-app-1-1-6', './functional_tests/published/test-1.1.6' ]
  id: 'test-app-build-1-1-6'
  waitFor: [ 'generator-run-1-1-6' ]
- name: test-app-1-1-6
  id: 'test-app-run-1-1-6'
  entrypoint: 'bash'
  args: [ '-c', '[[ "$(dotnet /app/test-1.1.6.dll)" == "Hello World 1.1.6!" ]]' ]
  waitFor: [ 'test-app-build-1-1-6' ]

# Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcore:1.1.6-${_TAG}'  
